/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kencana.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ItemType service. Represents a row in the &quot;Kencana_ItemType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kencana.lms.model.impl.ItemTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kencana.lms.model.impl.ItemTypeImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see ItemType
 * @see com.kencana.lms.model.impl.ItemTypeImpl
 * @see com.kencana.lms.model.impl.ItemTypeModelImpl
 * @generated
 */
public interface ItemTypeModel extends BaseModel<ItemType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a item type model instance should use the {@link ItemType} interface instead.
	 */

	/**
	 * Returns the primary key of this item type.
	 *
	 * @return the primary key of this item type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this item type.
	 *
	 * @param primaryKey the primary key of this item type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the item type ID of this item type.
	 *
	 * @return the item type ID of this item type
	 */
	public long getItemTypeId();

	/**
	 * Sets the item type ID of this item type.
	 *
	 * @param itemTypeId the item type ID of this item type
	 */
	public void setItemTypeId(long itemTypeId);

	/**
	 * Returns the item type name of this item type.
	 *
	 * @return the item type name of this item type
	 */
	@AutoEscape
	public String getItemTypeName();

	/**
	 * Sets the item type name of this item type.
	 *
	 * @param itemTypeName the item type name of this item type
	 */
	public void setItemTypeName(String itemTypeName);

	/**
	 * Returns the not for loan of this item type.
	 *
	 * @return the not for loan of this item type
	 */
	public boolean getNotForLoan();

	/**
	 * Returns <code>true</code> if this item type is not for loan.
	 *
	 * @return <code>true</code> if this item type is not for loan; <code>false</code> otherwise
	 */
	public boolean isNotForLoan();

	/**
	 * Sets whether this item type is not for loan.
	 *
	 * @param notForLoan the not for loan of this item type
	 */
	public void setNotForLoan(boolean notForLoan);

	/**
	 * Returns the cover ID of this item type.
	 *
	 * @return the cover ID of this item type
	 */
	public long getCoverId();

	/**
	 * Sets the cover ID of this item type.
	 *
	 * @param coverId the cover ID of this item type
	 */
	public void setCoverId(long coverId);

	/**
	 * Returns the checkout message of this item type.
	 *
	 * @return the checkout message of this item type
	 */
	@AutoEscape
	public String getCheckoutMessage();

	/**
	 * Sets the checkout message of this item type.
	 *
	 * @param checkoutMessage the checkout message of this item type
	 */
	public void setCheckoutMessage(String checkoutMessage);

	/**
	 * Returns the checkin message of this item type.
	 *
	 * @return the checkin message of this item type
	 */
	@AutoEscape
	public String getCheckinMessage();

	/**
	 * Sets the checkin message of this item type.
	 *
	 * @param checkinMessage the checkin message of this item type
	 */
	public void setCheckinMessage(String checkinMessage);

	/**
	 * Returns the rental rate of this item type.
	 *
	 * @return the rental rate of this item type
	 */
	public Double getRentalRate();

	/**
	 * Sets the rental rate of this item type.
	 *
	 * @param rentalRate the rental rate of this item type
	 */
	public void setRentalRate(Double rentalRate);

	/**
	 * Returns the company ID of this item type.
	 *
	 * @return the company ID of this item type
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this item type.
	 *
	 * @param companyId the company ID of this item type
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this item type.
	 *
	 * @return the group ID of this item type
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this item type.
	 *
	 * @param groupId the group ID of this item type
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this item type.
	 *
	 * @return the user ID of this item type
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this item type.
	 *
	 * @param userId the user ID of this item type
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this item type.
	 *
	 * @return the user uuid of this item type
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this item type.
	 *
	 * @param userUuid the user uuid of this item type
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this item type.
	 *
	 * @return the create date of this item type
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this item type.
	 *
	 * @param createDate the create date of this item type
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.kencana.lms.model.ItemType itemType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kencana.lms.model.ItemType> toCacheModel();

	@Override
	public com.kencana.lms.model.ItemType toEscapedModel();

	@Override
	public com.kencana.lms.model.ItemType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}