/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kencana.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Library service. Represents a row in the &quot;Kencana_Library&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kencana.lms.model.impl.LibraryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kencana.lms.model.impl.LibraryImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see Library
 * @see com.kencana.lms.model.impl.LibraryImpl
 * @see com.kencana.lms.model.impl.LibraryModelImpl
 * @generated
 */
public interface LibraryModel extends BaseModel<Library> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a library model instance should use the {@link Library} interface instead.
	 */

	/**
	 * Returns the primary key of this library.
	 *
	 * @return the primary key of this library
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this library.
	 *
	 * @param primaryKey the primary key of this library
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the library ID of this library.
	 *
	 * @return the library ID of this library
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this library.
	 *
	 * @param libraryId the library ID of this library
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the library name of this library.
	 *
	 * @return the library name of this library
	 */
	@AutoEscape
	public String getLibraryName();

	/**
	 * Sets the library name of this library.
	 *
	 * @param libraryName the library name of this library
	 */
	public void setLibraryName(String libraryName);

	/**
	 * Returns the group ID of this library.
	 *
	 * @return the group ID of this library
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this library.
	 *
	 * @param groupId the group ID of this library
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this library.
	 *
	 * @return the company ID of this library
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this library.
	 *
	 * @param companyId the company ID of this library
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the address1 of this library.
	 *
	 * @return the address1 of this library
	 */
	@AutoEscape
	public String getAddress1();

	/**
	 * Sets the address1 of this library.
	 *
	 * @param address1 the address1 of this library
	 */
	public void setAddress1(String address1);

	/**
	 * Returns the address2 of this library.
	 *
	 * @return the address2 of this library
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this library.
	 *
	 * @param address2 the address2 of this library
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the address3 of this library.
	 *
	 * @return the address3 of this library
	 */
	@AutoEscape
	public String getAddress3();

	/**
	 * Sets the address3 of this library.
	 *
	 * @param address3 the address3 of this library
	 */
	public void setAddress3(String address3);

	/**
	 * Returns the zipcode of this library.
	 *
	 * @return the zipcode of this library
	 */
	@AutoEscape
	public String getZipcode();

	/**
	 * Sets the zipcode of this library.
	 *
	 * @param zipcode the zipcode of this library
	 */
	public void setZipcode(String zipcode);

	/**
	 * Returns the city of this library.
	 *
	 * @return the city of this library
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this library.
	 *
	 * @param city the city of this library
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this library.
	 *
	 * @return the state of this library
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this library.
	 *
	 * @param state the state of this library
	 */
	public void setState(String state);

	/**
	 * Returns the country of this library.
	 *
	 * @return the country of this library
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this library.
	 *
	 * @param country the country of this library
	 */
	public void setCountry(String country);

	/**
	 * Returns the phone of this library.
	 *
	 * @return the phone of this library
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this library.
	 *
	 * @param phone the phone of this library
	 */
	public void setPhone(String phone);

	/**
	 * Returns the email of this library.
	 *
	 * @return the email of this library
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this library.
	 *
	 * @param email the email of this library
	 */
	public void setEmail(String email);

	/**
	 * Returns the website of this library.
	 *
	 * @return the website of this library
	 */
	@AutoEscape
	public String getWebsite();

	/**
	 * Sets the website of this library.
	 *
	 * @param website the website of this library
	 */
	public void setWebsite(String website);

	/**
	 * Returns the notes of this library.
	 *
	 * @return the notes of this library
	 */
	@AutoEscape
	public String getNotes();

	/**
	 * Sets the notes of this library.
	 *
	 * @param notes the notes of this library
	 */
	public void setNotes(String notes);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.kencana.lms.model.Library library);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kencana.lms.model.Library> toCacheModel();

	@Override
	public com.kencana.lms.model.Library toEscapedModel();

	@Override
	public com.kencana.lms.model.Library toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}