/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kencana.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MarcBatchUpload service. Represents a row in the &quot;Kencana_MarcBatchUpload&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kencana.lms.model.impl.MarcBatchUploadModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kencana.lms.model.impl.MarcBatchUploadImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see MarcBatchUpload
 * @see com.kencana.lms.model.impl.MarcBatchUploadImpl
 * @see com.kencana.lms.model.impl.MarcBatchUploadModelImpl
 * @generated
 */
public interface MarcBatchUploadModel extends BaseModel<MarcBatchUpload> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a marc batch upload model instance should use the {@link MarcBatchUpload} interface instead.
	 */

	/**
	 * Returns the primary key of this marc batch upload.
	 *
	 * @return the primary key of this marc batch upload
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this marc batch upload.
	 *
	 * @param primaryKey the primary key of this marc batch upload
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the marc batch upload ID of this marc batch upload.
	 *
	 * @return the marc batch upload ID of this marc batch upload
	 */
	public long getMarcBatchUploadId();

	/**
	 * Sets the marc batch upload ID of this marc batch upload.
	 *
	 * @param marcBatchUploadId the marc batch upload ID of this marc batch upload
	 */
	public void setMarcBatchUploadId(long marcBatchUploadId);

	/**
	 * Returns the group ID of this marc batch upload.
	 *
	 * @return the group ID of this marc batch upload
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this marc batch upload.
	 *
	 * @param groupId the group ID of this marc batch upload
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this marc batch upload.
	 *
	 * @return the company ID of this marc batch upload
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this marc batch upload.
	 *
	 * @param companyId the company ID of this marc batch upload
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create by of this marc batch upload.
	 *
	 * @return the create by of this marc batch upload
	 */
	public long getCreateBy();

	/**
	 * Sets the create by of this marc batch upload.
	 *
	 * @param createBy the create by of this marc batch upload
	 */
	public void setCreateBy(long createBy);

	/**
	 * Returns the created date of this marc batch upload.
	 *
	 * @return the created date of this marc batch upload
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this marc batch upload.
	 *
	 * @param createdDate the created date of this marc batch upload
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the processed of this marc batch upload.
	 *
	 * @return the processed of this marc batch upload
	 */
	public boolean getProcessed();

	/**
	 * Returns <code>true</code> if this marc batch upload is processed.
	 *
	 * @return <code>true</code> if this marc batch upload is processed; <code>false</code> otherwise
	 */
	public boolean isProcessed();

	/**
	 * Sets whether this marc batch upload is processed.
	 *
	 * @param processed the processed of this marc batch upload
	 */
	public void setProcessed(boolean processed);

	/**
	 * Returns the import date of this marc batch upload.
	 *
	 * @return the import date of this marc batch upload
	 */
	public Date getImportDate();

	/**
	 * Sets the import date of this marc batch upload.
	 *
	 * @param importDate the import date of this marc batch upload
	 */
	public void setImportDate(Date importDate);

	/**
	 * Returns the import by user ID of this marc batch upload.
	 *
	 * @return the import by user ID of this marc batch upload
	 */
	public long getImportByUserId();

	/**
	 * Sets the import by user ID of this marc batch upload.
	 *
	 * @param importByUserId the import by user ID of this marc batch upload
	 */
	public void setImportByUserId(long importByUserId);

	/**
	 * Returns the import by user uuid of this marc batch upload.
	 *
	 * @return the import by user uuid of this marc batch upload
	 * @throws SystemException if a system exception occurred
	 */
	public String getImportByUserUuid() throws SystemException;

	/**
	 * Sets the import by user uuid of this marc batch upload.
	 *
	 * @param importByUserUuid the import by user uuid of this marc batch upload
	 */
	public void setImportByUserUuid(String importByUserUuid);

	/**
	 * Returns the partial import of this marc batch upload.
	 *
	 * @return the partial import of this marc batch upload
	 */
	public boolean getPartialImport();

	/**
	 * Returns <code>true</code> if this marc batch upload is partial import.
	 *
	 * @return <code>true</code> if this marc batch upload is partial import; <code>false</code> otherwise
	 */
	public boolean isPartialImport();

	/**
	 * Sets whether this marc batch upload is partial import.
	 *
	 * @param partialImport the partial import of this marc batch upload
	 */
	public void setPartialImport(boolean partialImport);

	/**
	 * Returns the file count of this marc batch upload.
	 *
	 * @return the file count of this marc batch upload
	 */
	public int getFileCount();

	/**
	 * Sets the file count of this marc batch upload.
	 *
	 * @param fileCount the file count of this marc batch upload
	 */
	public void setFileCount(int fileCount);

	/**
	 * Returns the description of this marc batch upload.
	 *
	 * @return the description of this marc batch upload
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this marc batch upload.
	 *
	 * @param description the description of this marc batch upload
	 */
	public void setDescription(String description);

	/**
	 * Returns the record count of this marc batch upload.
	 *
	 * @return the record count of this marc batch upload
	 */
	public int getRecordCount();

	/**
	 * Sets the record count of this marc batch upload.
	 *
	 * @param recordCount the record count of this marc batch upload
	 */
	public void setRecordCount(int recordCount);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.kencana.lms.model.MarcBatchUpload marcBatchUpload);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kencana.lms.model.MarcBatchUpload> toCacheModel();

	@Override
	public com.kencana.lms.model.MarcBatchUpload toEscapedModel();

	@Override
	public com.kencana.lms.model.MarcBatchUpload toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}