/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kencana.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PatronCategory service. Represents a row in the &quot;Kencana_PatronCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kencana.lms.model.impl.PatronCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kencana.lms.model.impl.PatronCategoryImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see PatronCategory
 * @see com.kencana.lms.model.impl.PatronCategoryImpl
 * @see com.kencana.lms.model.impl.PatronCategoryModelImpl
 * @generated
 */
public interface PatronCategoryModel extends BaseModel<PatronCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a patron category model instance should use the {@link PatronCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this patron category.
	 *
	 * @return the primary key of this patron category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this patron category.
	 *
	 * @param primaryKey the primary key of this patron category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the patron category ID of this patron category.
	 *
	 * @return the patron category ID of this patron category
	 */
	public long getPatronCategoryId();

	/**
	 * Sets the patron category ID of this patron category.
	 *
	 * @param patronCategoryId the patron category ID of this patron category
	 */
	public void setPatronCategoryId(long patronCategoryId);

	/**
	 * Returns the patron category name of this patron category.
	 *
	 * @return the patron category name of this patron category
	 */
	@AutoEscape
	public String getPatronCategoryName();

	/**
	 * Sets the patron category name of this patron category.
	 *
	 * @param patronCategoryName the patron category name of this patron category
	 */
	public void setPatronCategoryName(String patronCategoryName);

	/**
	 * Returns the notes of this patron category.
	 *
	 * @return the notes of this patron category
	 */
	@AutoEscape
	public String getNotes();

	/**
	 * Sets the notes of this patron category.
	 *
	 * @param notes the notes of this patron category
	 */
	public void setNotes(String notes);

	/**
	 * Returns the group ID of this patron category.
	 *
	 * @return the group ID of this patron category
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this patron category.
	 *
	 * @param groupId the group ID of this patron category
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this patron category.
	 *
	 * @return the company ID of this patron category
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this patron category.
	 *
	 * @param companyId the company ID of this patron category
	 */
	public void setCompanyId(long companyId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.kencana.lms.model.PatronCategory patronCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kencana.lms.model.PatronCategory> toCacheModel();

	@Override
	public com.kencana.lms.model.PatronCategory toEscapedModel();

	@Override
	public com.kencana.lms.model.PatronCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}