/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kencana.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Patron service. Represents a row in the &quot;Kencana_Patron&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kencana.lms.model.impl.PatronModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kencana.lms.model.impl.PatronImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see Patron
 * @see com.kencana.lms.model.impl.PatronImpl
 * @see com.kencana.lms.model.impl.PatronModelImpl
 * @generated
 */
public interface PatronModel extends BaseModel<Patron> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a patron model instance should use the {@link Patron} interface instead.
	 */

	/**
	 * Returns the primary key of this patron.
	 *
	 * @return the primary key of this patron
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this patron.
	 *
	 * @param primaryKey the primary key of this patron
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the patron ID of this patron.
	 *
	 * @return the patron ID of this patron
	 */
	public long getPatronId();

	/**
	 * Sets the patron ID of this patron.
	 *
	 * @param patronId the patron ID of this patron
	 */
	public void setPatronId(long patronId);

	/**
	 * Returns the card number of this patron.
	 *
	 * @return the card number of this patron
	 */
	@AutoEscape
	public String getCardNumber();

	/**
	 * Sets the card number of this patron.
	 *
	 * @param cardNumber the card number of this patron
	 */
	public void setCardNumber(String cardNumber);

	/**
	 * Returns the user ID of this patron.
	 *
	 * @return the user ID of this patron
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this patron.
	 *
	 * @param userId the user ID of this patron
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this patron.
	 *
	 * @return the user uuid of this patron
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this patron.
	 *
	 * @param userUuid the user uuid of this patron
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this patron.
	 *
	 * @return the group ID of this patron
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this patron.
	 *
	 * @param groupId the group ID of this patron
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this patron.
	 *
	 * @return the company ID of this patron
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this patron.
	 *
	 * @param companyId the company ID of this patron
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the library ID of this patron.
	 *
	 * @return the library ID of this patron
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this patron.
	 *
	 * @param libraryId the library ID of this patron
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the expiry date of this patron.
	 *
	 * @return the expiry date of this patron
	 */
	public Date getExpiryDate();

	/**
	 * Sets the expiry date of this patron.
	 *
	 * @param expiryDate the expiry date of this patron
	 */
	public void setExpiryDate(Date expiryDate);

	/**
	 * Returns the patron category ID of this patron.
	 *
	 * @return the patron category ID of this patron
	 */
	public long getPatronCategoryId();

	/**
	 * Sets the patron category ID of this patron.
	 *
	 * @param patronCategoryId the patron category ID of this patron
	 */
	public void setPatronCategoryId(long patronCategoryId);

	/**
	 * Returns the patron status ID of this patron.
	 *
	 * @return the patron status ID of this patron
	 */
	public long getPatronStatusId();

	/**
	 * Sets the patron status ID of this patron.
	 *
	 * @param patronStatusId the patron status ID of this patron
	 */
	public void setPatronStatusId(long patronStatusId);

	/**
	 * Returns the patron note of this patron.
	 *
	 * @return the patron note of this patron
	 */
	@AutoEscape
	public String getPatronNote();

	/**
	 * Sets the patron note of this patron.
	 *
	 * @param patronNote the patron note of this patron
	 */
	public void setPatronNote(String patronNote);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.kencana.lms.model.Patron patron);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kencana.lms.model.Patron> toCacheModel();

	@Override
	public com.kencana.lms.model.Patron toEscapedModel();

	@Override
	public com.kencana.lms.model.Patron toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}