/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kencana.lms.model.impl;

import com.kencana.lms.model.CatalogTemplateTag;
import com.kencana.lms.service.CatalogTemplateTagLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the CatalogTemplateTag service. Represents a row in the &quot;Kencana_CatalogTemplateTag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CatalogTemplateTagImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see CatalogTemplateTagImpl
 * @see com.kencana.lms.model.CatalogTemplateTag
 * @generated
 */
public abstract class CatalogTemplateTagBaseImpl
	extends CatalogTemplateTagModelImpl implements CatalogTemplateTag {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a catalog template tag model instance should use the {@link CatalogTemplateTag} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			CatalogTemplateTagLocalServiceUtil.addCatalogTemplateTag(this);
		}
		else {
			CatalogTemplateTagLocalServiceUtil.updateCatalogTemplateTag(this);
		}
	}
}